default:
  cache:
    key: terraform-cache
    paths:
      - .terraform/

stages:
  - init
  - validate
  - plan

variables:
  TF_IN_AUTOMATION: "true"
  TF_LOG: "DEBUG"

init:
  stage: init
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  tags:
    - docker
  script:
    - terraform --version
    - terraform init
    - ls -la

validate:
  stage: validate
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  tags:
    - docker
  dependencies:
    - init
  script:
    - terraform validate

plan:
  stage: plan
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  tags:
    - docker
  dependencies:
    - init
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan
    expire_in: 1 hour