validate:
  stage: validate
  image: hashicorp/terraform:light
  tags:
    - docker
  script:
    - terraform init
    - terraform validate

plan:
  stage: plan
  image: hashicorp/terraform:light
  tags:
    - docker
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan
    expire_in: 1 hour